### PR TITLE
#1742 refactoring and making builder optional

### LINKED ISSUE #1742: MapStruct 1.3.0.Final produces uncompilable code when using Java 11 + Lombok 1.18.6
My setup: Java 11.02, Gradle 5.2.1, MapStruct 1.3.0.Final, Lombok 1.18.6 and Spring Boot 2.3.1.

**build.gradle**

```groovy
plugins {
    id "net.ltgt.apt" version "0.21"
    id "net.ltgt.apt-idea" version "0.21"
}

...

/* Lombok */
compileOnly "org.projectlombok:lombok:${lombokVersion}"
annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

/* Map Struct */
implementation "org.mapstruct:mapstruct-jdk8:${mapstructVersion}"
annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
```

**FirstEntity.java**
```java
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@Entity
@Table(name="first_entity")
public class FirstEntity {

  @Id
  private Long id;

  @ManyToOne
  @JoinColumn(name="second_entity_id")
  private SecondEntity secondEntity;

}
```

**FirstEntityDTO.java**
```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FirstEntityDTO {

  private Long id;
  private SecondEntityDTO secondEntity;

}
```

**SecondEntity.java**
```java
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "id")
@Entity
@Table(name="second_entity")
public class SecondEntity {

  @Id
  private Long id;

}
```

**SecondEntityDTO.java**
```java
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SecondEntityDTO {

  private Long id;

}
```

**EntityMapper.java**
```java
@Mapper(
        unmappedTargetPolicy = ReportingPolicy.IGNORE,
        componentModel = "spring"
)
public interface EntityMapper {

    FirstEntity updateEntity(FirstEntityDTO entityDto, @MappingTarget FirstEntity entity);
}
```

**Generated code, MapStruct 1.3.0.Final**
```java
if (entityDto.getSecondEntity() != null ) {
    if (entity.getSecondEntity() == null ) {
        entity.setSecondEntity( SecondEntity.builder() ); //compilation error: incompatible types
    }
    secondEntityDTOToSecondEntity( entityDto.getSecondEntity(), entity.getSecondEntity());
}
```

**Generated code, MapStruct 1.2.0.Final**
```java
if (entityDto.getSecondEntity() != null ) {
    if (entity.getSecondEntity() == null ) {
        entity.setSecondEntity( new SecondEntity() ); //success
    }
    secondEntityDTOToSecondEntity( entityDto.getSecondEntity(), entity.getSecondEntity());
}
```
_**As a workaround, I use MapStruct 1.2.0.Final now.**_

### PR DESCRIPTION
**Pull request by sjaakd**
Currently the accessor type is defined in PropertyMapper while it should be an intrinsic property of Accessor. Types are fetched and derived in context (again) all-over-the-place.. Sometimes that requires the parent type again and even the mapping method (to derive in context and resolve generics).

Next, builderType is part of type. One could say there is a relation from builderType to Type but not the other way around. A builderType could be in a completely different package. It's still not as I want.. But I managed to move the builderType (mostly) to the place were its relevant: the `BeanMappingMethod`. 

Done!

I'm still not completely happy with the number of places were I do need to consult the typeFactory for the `effectiveType` or the `builderType`. This indicates a bad separation of concerns. Probably stemming from the fact that we do analyse a nested target and try to find the associated types in `TargetReference`. I think that in the end `TargetReference` and `SourceReference` should be handled in the `BeanMappingMethod` and not in `Mapping` upfront but in the context of the `BeanMappingMethod`.

I experimented with making annotations and annotation fields `Optional`. I think we should apply this pattern, because we keep on doing null checks all over the place.

Fixes #1742

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java [hunk 1]
```diff
@@ -58,18 +77,18 @@ public static MethodReference getFactoryMethod( Method method,
                 method,
                 getAllAvailableMethods( method, ctx.getSourceModel() ),
                 java.util.Collections.<Type> emptyList(),
-                targetType.getEffectiveType(),
+                alternativeTarget,
                 SelectionCriteria.forFactoryMethods( selectionParameters ) );
 
         if (matchingFactoryMethods.isEmpty()) {
-            return findBuilderFactoryMethod( targetType );
+            return null;
```
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java]: Why return `null` here?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java [hunk 2]
```diff
@@ -82,11 +81,11 @@ public ForgedMethod(String name, Type sourceType, Type returnType, MapperConfigu
      * @param mappingOptions the mapping options for this method
      * @param forgedNameBased forges a name based (matched) mapping method
      */
-    public ForgedMethod(String name, Type sourceType, Type returnType, MapperConfiguration mapperConfiguration,
-                        ExecutableElement positionHintElement, List<Parameter> additionalParameters,
-                        ParameterProvidedMethods parameterProvidedMethods, ForgedMethodHistory history,
-                        MappingOptions mappingOptions, boolean forgedNameBased) {
-        String sourceParamName = Strings.decapitalize( sourceType.getName() );
+     public ForgedMethod(String name, Type sourceType, Type returnType, MapperConfiguration mapperConfiguration,
```
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java]: Are this formatting changes really needed?

File: processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java [hunk 3]
```diff
@@ -113,18 +113,7 @@ public void builderMappingMapperConfigDefined() {
         TooManyBuilderCreationMethodsMapper.class
     })
     @ExpectedCompilationOutcome(value = CompilationResult.SUCCEEDED,
-        // We have 2 diagnostics, as we don't do caching of the types, so a type is processed multiple types
         diagnostics = {
-            @Diagnostic(
```
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java]: So we no longer report this warning?

File: core/src/main/java/org/mapstruct/Builder.java [hunk 4]
```diff
@@ -29,4 +29,12 @@
...
      */
     String buildMethod() default "build";
+
+    /**
+     * Toggling builders on / off. Builders are sometimes used solely for unit testing (fluent testdata)
+     * MapStruct will need to use the regular getters /setters in that case.
+     *
+     * @return when true, no builder patterns will be applied
+     */
+    boolean noBuilder() default false;
```
Comment (filiphr) [inline core/src/main/java/org/mapstruct/Builder.java]: How about `disableBuilder`? For some reason `noBuilder` doesn't really stick. I am open to other suggestions as well.

**Comment by filiphr** [comment]
I forgot to mention. This PR would also solve https://github.com/mapstruct/mapstruct/issues/1661, right?

**Comment by sjaakd** [comment]
> I forgot to mention. This PR would also solve #1661, right?

it does..

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java (hunk 2 above)
Comment (sjaakd) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java]: No they aren't.. I'll remove them..

**Comment by filiphr** [comment]
For #1661 let's also add an annotation processor option. So this would partially solve it.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java (hunk 2 above)
Comment (sjaakd) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java]: I did a lot of trial and error here.. So I guess there was (in one of my commits) an extra param..

File: processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java (hunk 1 above)
Comment (sjaakd) [reply processor/src/main/java/org/mapstruct/ap/internal/model/ObjectFactoryMethodResolver.java]: I changed the design here a bit.. If you look at the call site: 

```java
        private MethodReference getFactoryMethod(Type returnTypeImpl, SelectionParameters selectionParameters) {
            MethodReference factoryMethod = ObjectFactoryMethodResolver.getFactoryMethod( method,
                            returnTypeImpl,
                            selectionParameters,
                            ctx
            );
            if ( factoryMethod == null && returnTypeBuilder != null ) {
                factoryMethod = ObjectFactoryMethodResolver.getBuilderFactoryMethod( method, returnTypeBuilder );
            }

            return factoryMethod;
        }
```

You'll find that there's more to check.. Error handling for not-found methods takes place at the call sites of this method. At the other hand, when there's too many qualifying methods, we know its wrong anyway...

File: processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java (hunk 3 above)
Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java]: correction: since we only resolve the builder once, we don't report the duplicate anymore :smile:

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java (hunk 2 above)
Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/ForgedMethod.java]: makes sense

File: processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java (hunk 3 above)
Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java]: I am not quite following. I think what the test is trying to show that if there are multiple builders (when we try to resolve) we are going to output a warning message. It is not about duplicates, there are 2 potential builder creation methods here.

Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/builder/multiple/MultipleBuilderMapperTest.java]: I see it now. There is another `@Diagnostic` with the exact same error

**Comment by filiphr** [comment]
Thanks for the updates. LGTM for merging

**Comment by chris922** [comment]
I just had a quick glance at your changes, looks awesome. Thanks @sjaakd !
