### PR TITLE
#1153 Do not use invalid TargetReferences when creating nested target mappings

### LINKED ISSUE #1153: Exception when mapping non existing target..
Internal error in the mapping processor: java.util.NoSuchElementException at
     java.util.ArrayList$Itr.next(ArrayList.java:854)  	at
     org.mapstruct.ap.internal.util.Collections.first(Collections.java:77)  	at
     org.mapstruct.ap.internal.model.NestedTargetPropertyMappingHolder$Builder.groupByTargetReferences(NestedTargetPropertyMappingHolder.java:288)  	at
     org.mapstruct.ap.internal.model.NestedTargetPropertyMappingHolder$Builder.build(NestedTargetPropertyMappingHolder.java:133)  	at
     org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedNestedTargetMapping(BeanMappingMethod.java:359)  	at
     org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.handleDefinedMappings(BeanMappingMethod.java:325)  	at
     org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:137)  	at
     org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:373)  	at
     org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)  	at
     org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)  	at
     org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:80)  	at
     org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:280)  	at
     org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:260)  	at
     org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:226)  	at
     org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:162)  	at
     com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)  	at
     com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)  	at
     com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at
     com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)  	at
     com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)  	at
     com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at
     com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)  	at
     com.sun.tools.javac.main.Main.compile(Main.java:523)  	at
     com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)  	at
     com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)  	at
     org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)  	at
     org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:171)  	at
     org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)  	at
     org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)  	at
     org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)  	at
     org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)  	at
     org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)  	at
     org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)  	at
     org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)  	at
     org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)  	at
     org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)  	at
     org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)  	at
     org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)  	at
     org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)  	at
     org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)  	at
     org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)  	at
     org.apache.maven.cli.MavenCli.main(MavenCli.java:141)  	at
     sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at
     sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at
     sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at
     java.lang.reflect.Method.invoke(Method.java:498)  	at
     org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)  	at
     org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)  	at
     org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)  	at
     org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)  

Problem occurs when a nested property is accessed on target side which does not exist.

### PR DESCRIPTION
**Pull request by filiphr**
* Move the error generation for the invalid TargetReference into the BuilderFromTargetMapping
* TargetReference will strip the first entry name in the following cases only if the first entry name matches the MappingTarget parameter, or for reverse mappings it matches the source parameter name
* Pass the reverse source parameter when initializing a reverse mapping

Fixes #1153.

This PR and #1168 are changing the same code.

### CODE REVIEW

**Comment by filiphr** [comment]
Just as a note, this PR does not change the way we report the error messages. They stay the same both for nested target properties and non-nested target properties. I have created #1185 for a discussion about how we can improve those messages.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 1]
```diff
@@ -112,24 +136,31 @@ public TargetReference build() {
...
+                // This is called only for reporting errors
+                getTargetEntries( resultType, targetPropertyNames, true );
+            }
+
             // foundEntryMatch = isValid, errors are handled in the BeanMapping, where the error context is known
             return new TargetReference( parameter, entries, foundEntryMatch );
         }
 
-        private List<PropertyEntry> getTargetEntries(Type type, String[] entryNames) {
+        private List<PropertyEntry> getTargetEntries(Type type, String[] entryNames, boolean reportError) {
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: would 'doErrorAnalysis' suit better as a parameter name than `reportError`?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 2]
```diff
@@ -142,46 +173,150 @@ public TargetReference build() {
...
+         * @param initial for which a next type should be found
+         * @param targetWriteAccessor the write accessor
+         * @param targetReadAccessor the read accessor
+         * @param isLast whether this is the call for the last accessor
+         *
+         * @return the next type that should be used for finding a property entry
+         */
+        private Type findNextType(Type initial, Accessor targetWriteAccessor,
+            Accessor targetReadAccessor, boolean isLast) {
+            if ( !isLast && targetWriteAccessor == null ) {
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: so... do we need to check this then? Can it happen by SPI mis-use? I presume it is checked prior to calling this method.. right?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 1 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: Well the error analysis is always done, we need to know when to report the error. We can't do it on the first iteration as we can theoretically have the target property name in the mapping.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 3]
```diff
@@ -112,24 +136,31 @@ public TargetReference build() {
...
+                entries = getTargetEntries( resultType, targetPropertyNames, false );
                 foundEntryMatch = (entries.size() == targetPropertyNames.length);
             }
 
+            if ( !foundEntryMatch ) {
+                // This is called only for reporting errors
+                getTargetEntries( resultType, targetPropertyNames, true );
+            }
+
             // foundEntryMatch = isValid, errors are handled in the BeanMapping, where the error context is known
```
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: Note to me: this needs to be removed, errors are handled here not in the `BeanMapping`

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 2 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: We don't really need to check it. If this condition is `true` then we would have already stopped on line 188. The condition is unreachable unless we change something in the lines 178 to 180. I mostly added during implementation in case I mess something up. If you think that we should remove it, I can do it.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 1 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: maybe `doReportError` or `shouldReportError`?

**Comment by filiphr** [comment]
Thanks a lot for the review @sjaakd. I'll update the PR with the changes tomorrow.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 1 above)
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: ah..  now its more clear to me.. I thought that you established there was an error and now you need to determine where. But what you mean is that you are not yet sure if it is an error in the first run(s). So what about 'isLastAttempt' ?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 2 above)
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: I would remove it. If you made a mistake. its sometimes better to let it fail drastically e.g. by a null pointer.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 1 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: There is always an error if the if condition on lines 178 to 180 evaluates to `true`. However, we call  `getTargetEntries` twice without reporting the error and if there is no `foundEntryMatcht` we need to go again just to report the error. `isLastAttempt` for me it means that it is the last attempt to get the target entries, but when we report the error it is not last attempt, it is just report the place with the error.  What about just to store  the error message in the builder and just report that? Without adding the `boolean` to the methods it self?

Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: ok.. And then you would check first thing in `getTargetReferences` whether the boolean is set before continuing? BTW: would `resolveTargetRefences` not be a better name?

Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: The boolean is checked by using `TargetReference#isValid()`, if it is not valid then we report in the `NestedTargetHolder` that an error occurred. The same way that we do for non nested. I just moved the error handling in the `TargetReference` because the error handling would have been duplicated between the nested and non-nested handling. 

As for the name, I think that `getTargetEntries` is good because it is in the builder and it actually gives back the `PropertyEntry`(ies) for the `TargetReference`. It is not a new methods, it was there from before...

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 4]
```diff
@@ -142,25 +148,26 @@ public TargetReference build() {
...
             if ( !foundEntryMatch && segments.length > 1
                 && matchesSourceOrTargetParameter( segments[0], parameter, reverseSourceParameter, isReverse ) ) {
                 targetPropertyNames = Arrays.copyOfRange( segments, 1, segments.length );
-                entries = getTargetEntries( resultType, targetPropertyNames, false );
+                entries = getTargetEntries( resultType, targetPropertyNames );
                 foundEntryMatch = (entries.size() == targetPropertyNames.length);
             }
 
-            if ( !foundEntryMatch ) {
+            if ( !foundEntryMatch && errorMessage != null) {
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: what message will be printend if `foundEntryMatch==false` and `errorMessage==null`?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 5]
```diff
@@ -142,25 +148,26 @@ public TargetReference build() {
...
                 // This is called only for reporting errors
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: is this comment still useful?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java [hunk 6]
```diff
@@ -142,25 +148,26 @@ public TargetReference build() {
             // 3. @MappingTarget, with
             // 4. or without parameter name.
             String[] targetPropertyNames = segments;
-            List<PropertyEntry> entries = getTargetEntries( resultType, targetPropertyNames, false );
+            List<PropertyEntry> entries = getTargetEntries( resultType, targetPropertyNames );
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: `getTargetEntries` .. I still think that `resolveTargetEntries` is better.. There is some analysis involved and its not a plain getter..

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 5 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: Nope, I'll remove it :). Thanks

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 4 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: Nothing will be printed then. Before was the same, if this happens that means that the `targetWriteAccessor` and `targetReadAccessor` are not `null`, if that is the case, then the condition between lines 185 and 187 would have been `false`.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java (hunk 6 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/TargetReference.java]: You are looking at a diff between my two commits, right now it is the same as it was before there is no change in the invoking of the method and the method itself. If you think that rename is needed, I can rename it to `resolveTargetEntries`.

**Comment by sjaakd** [comment]
Nope ! Just go ahead with the merge!

Verstuurd vanaf mijn iPhone

**Comment by filiphr** [comment]
Thanks for the review @sjaakd :)
