### PR TITLE
#1826: fixed null pointer in nested property mapping when using prese…

### LINKED ISSUE #1826: Null pointer exception in nested property mapping method with presence check
Given the following object structures:
```
SourceParent                        Target
    |_ SourceChild                       |_Content
         |_ Content 
```
If you try to map `SourceParent->SourceChild->Content` to `Target->Content` and also are using presence tracking you will get a null pointer if `SourceChild` is present but null.  

The NestedPropertyMappingMethod.ftl is missing a null check before checking presence.  I have fixed this and will open a PR shortly.

### PR DESCRIPTION
**Pull request by jakraska**
Present but null fields could cause null pointer exceptions when mapping nested properties. 

Fixes #1826

### CODE REVIEW

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+ * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
+ */
+package org.mapstruct.ap.test.bugs._1826;
+
+import org.mapstruct.Mapper;
+import org.mapstruct.Mapping;
+import org.mapstruct.NullValueCheckStrategy;
+import org.mapstruct.factory.Mappers;
+
+@Mapper(nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS)
```
Comment (sjaakd) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: I think you need to add another test case (and possibly some additional coding) to test whether the `nullValueCheckStrategy` actually works.

File: processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl [hunk 2]
```diff
@@ -12,7 +12,7 @@
     }
 <#list propertyEntries as entry>
     <#if entry.presenceCheckerName?? >
-    if ( !<@localVarName index=entry_index/>.${entry.presenceCheckerName}() ) {
+    if ( <@localVarName index=entry_index/> == null || !<@localVarName index=entry_index/>.${entry.presenceCheckerName}() ) {
```
Comment (sjaakd) [inline processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: I guess the `||` should be `&&` in order to stay in line with other occurrences.

Comment (jakraska) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: If i change this to &&, it won't fix the null pointer.    This is the code that gets generated for the test case where `hasSourceChild` is `true` and `sourceChild` is `null`

```
 private String sourceParentSourceChildContent(SourceParent sourceParent) {
        if ( sourceParent == null ) {
            return null;
        }
        if ( sourceParent == null || !sourceParent.hasSourceChild() ) {
            return null;
        }
        SourceChild sourceChild = sourceParent.getSourceChild();
        if ( sourceChild == null || !sourceChild.hasContent() ) {
            return null;
        }
        String content = sourceChild.getContent();
        return content;
    }
```

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java (hunk 1 above)
Comment (jakraska) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: To be honest, I dont think the NullValueCheckStrategy property effects this code.  The source that gets generated here is identical without / without the strategy defined, so i can remove this from the test mapper definition if that helps.   I don't see any switches in the template that change the logic based on the  NullValueCheckStrategy setting.  What exactly would i be testing here?

File: processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl (hunk 2 above)
Comment (filiphr) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: Why `hasSourceChild` returns `true` when `sourceChild` is `null`?

Comment (filiphr) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: I missed the discussion in the issue before writing this. @jakraska explained everything in https://github.com/mapstruct/mapstruct/issues/1826#issuecomment-495920222. That is what I suspected as well.

Comment (sjaakd) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: > If i change this to &&, it won't fix the null pointer. This is the code that gets generated for the test case where `hasSourceChild` is `true` and `sourceChild` is `null`

Ok. You are right.. You break the flow (return) in stead of "setting some target".. Its de good all " de morgan"  again :smile:.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java (hunk 1 above)
Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: I think that you should control the addition of the null check, having a possibility to opt-in. That would be  in line with our documentation. 

> I don't see any switches in the template that change the logic based on the NullValueCheckStrategy setting. What exactly would i be testing here?

I think that should be added to stay in line with the documentation and other places... It is present in the `PropertyMapping` and then `NullValueCheck` can be added to the creation of the backing bean of the template. BTW: this being a non update method it is the `NullValueCheckStrategy` you're after... not the `NullValuePropertyCheckStrategy`.

Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: Hold on before you implement this.. Perhaps you're right.. I added also some comment to the issue on this.

Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: @sjaakd I am not sure that we need something special for this. This is only happening for extracting nested source value, if we add another option it might be overcomplicating it 😄

File: processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl (hunk 2 above)
Comment (filiphr) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: I have only one small remark about how the generated code looks like. The `sourceParent` is checked twice for different to `null`. Maybe we need to skip the second check. I think it can be done with an explicit check for `entry_index == 0`. WDYT @jakraska?

Comment (jakraska) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: @filiphr  - yes i agree with the concern about the duplicate null check.  I left it in there to keep the template logic / change as readable as possible, but i'm definitely happy to add that condition in if you prefer.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java (hunk 1 above)
Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: 👍 ok.. Agreed.

Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: @jakraska then my only remaining comment is to remove argument of the `@Mapper`..

Comment (jakraska) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: @sjaakd will do

Comment (jakraska) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_1826/Issue1826Mapper.java]: The extra parameters have been removed from the @mapper annotation.

File: processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl (hunk 2 above)
Comment (jakraska) [reply processor/src/main/resources/org/mapstruct/ap/internal/model/NestedPropertyMappingMethod.ftl]: I updated the template.  the generated code now looks like this:
```
    private String sourceParentSourceChildContent(SourceParent sourceParent) {
        if ( sourceParent == null ) {
            return null;
        }
        if ( !sourceParent.hasSourceChild() ) {
            return null;
        }
        SourceChild sourceChild = sourceParent.getSourceChild();
        if ( sourceChild == null || !sourceChild.hasContent() ) {
            return null;
        }
        String content = sourceChild.getContent();
        return content;
    }
```

**Comment by filiphr** [comment]
Latest changes look good to me. Thanks @jakraska. I would leave it to @sjaakd to do the merge (as he already did most of the review)

**Comment by sjaakd** [comment]
@jakraska .. thanks for your contribution.
