### PR TITLE
#1367 aligning @InheritConfiguration and @InheritReverseConfiguration with AUTO_INHERIT_ALL_FROM_CONFIG.

### LINKED ISSUE #1367: Shared configuration not applied when using InheritInverseConfiguration
I am trying to make both features "Shared Configuration" and "Inverse Mapping" work together, without success. ( Version used:  1.2.0.Final )
I use MapStruct in my project in order to handle mapping between domain entities layer (JPA entities) and REST resources layer (simple DTOs used by REST/JSON API).
- shared configuration:
Both entities and dtos layers have a root base class that handle common properties, so I have implemented a MapperConfig to handle mapping rules for these fields : 
```
@MapperConfig(unmappedTargetPolicy = ReportingPolicy.WARN,
        mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG)
public interface EntityToDtoMappingConfig {
    
    @Mapping(target = "dbId", source = "id")
    @Mapping(target = "links", ignore = true)
    BaseDto entityToDto(final BaseEntity entity);
    
    @Mapping(target = "id", source = "dbId")
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "creationDate", ignore = true)
    @Mapping(target = "lastModifiedBy", constant = "restApiUser") // force modifiedBy with restApiUser constant
    @Mapping(target = "lastModifiedDate", ignore = true)
    public BaseEntity dtoToEntity(BaseDto dto);
    
}
```
- Inverse Mapping
I use @InheritInverseConfiguration in order to simplify "mapFrom" methods definition: generally all mapping rules are defined on the "mapTo" methods, so "mapFrom" methods can be defined simply with "inverse mapping" :
```
@Mapper(config = EntityToDtoMappingConfig.class)
public abstract class CarMapper {

    @Mapping(source = "manufacturer", target = "maker")
    @Mapping(source = "numberOfSeats", target = "seatCount")
    abstract public CarDto mapTo(Car car);
    
    @InheritInverseConfiguration(name = "mapTo")
    // inheritInvers configuration should map both maker and seatCount properties.
    // additional mapping should also be inherited from   EntityToDtoMappingConfig.dtoToEntity method, BUT IT DOES NOT SEEM TO WORK
    abstract Car mapFrom(CarDto carDto);
    
}
```

Mapping from Entity to DTO is working fine: inheritance is handled correctly and mapping rules from EntityToDtoMappingConfig  are appended to mapping rules defined on CarMapper.mapTo method.

But mapping from DTO to Entity is not working as expected :  mapping rules defined in the EntityToDtoMappingConfig  are not applied.

Question : is there a limitation when using InheritInverseConfiguration that prevent us using shared configuration mechanisme?  or is this a bug ?

I have shared a concrete and simple project on GitHub to demonstrate this issue : see  https://github.com/mricciuti/sandbox-mapstruct

Thanks by advance.

### PR DESCRIPTION
**Pull request by sjaakd**
Fixes #1367 

Whereas its not possible to combine forward and reverse explicit configurations (you get a warning:  `Method cannot be annotated with both a @InheritConfiguration and @InheritInverseConfiguration`) it seems to be possible with the current auto-inheritance options. Here you have the possibilities: `AUTO_INHERIT_FROM_CONFIG`, `AUTO_INHERIT_REVERSE_FROM_CONFIG`, and **`AUTO_INHERIT_ALL_FROM_CONFIG`** .

This PR removes that restriction and aligns the strategy for auto inheritance. So it will be possible to define an `@InheritConfiguration` together with `@InheritReverseConfiguration` on  the same method.

Forward mappings (`@InheritConfiguration`) takes precedence over reverse mappings (`@InheritInverseConfiguration`)

### CODE REVIEW

**Comment by filiphr** [comment]
@sjaakd I'll review this ASAP

File: processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapperTest.java [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    }
+
+    @Test
+    public void testMapDtoToEntity() {
+        CarEntity car = CarMapper.MAPPER.mapFrom( newCarDto() );
+        assertThat( car.getId() ).isEqualTo( 9L );
+        assertThat( car.getManufacturer() ).isEqualTo( "Nissan" );
+        assertThat( car.getNumberOfSeats() ).isEqualTo( 5 );
+
+        // following assertion fails :  createdBy property is not set.
```
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapperTest.java]: Do we still need this line and the one below?

Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/inheritfromconfig/multiple/CarMapperTest.java]: I'll remove that one.. You're right..

**Comment by sjaakd** [comment]
@filiphr .. thanks for the review. I'll fix the issue an wait a couple of days for the response of @mricciuti. I'll proceed to merge on sunday evening or monday.

**Comment by sjaakd** [comment]
squashed
