### PR TITLE
#3331 Do not handle defined mappings if the result type is abstract due to runtime exception subclass exhaustive strategy

### LINKED ISSUE #3331: Abstract class fields mapping issues
### Expected behavior

Mapstruct can map fields of abstract classes

### Actual behavior

Mapstruct is not mapping fields of abstract classes - various problems occur

### Steps to reproduce the problem

Source classes:
```java
public abstract class Vehicle {
	private final String name;
	Vehicle(String name) {
		this.name = name;
	}
	public String getName() {
		return name;
	}
}

public class Car extends Vehicle {
	private final int numOfDoors;
	Car(String name, int numOfDoors) {
		super(name);
		this.numOfDoors = numOfDoors;
	}
	public int getNumOfDoors() {
		return numOfDoors;
	}
}

public class Motorbike extends Vehicle {
	private final boolean allowedForMinor;
	Motorbike(String name, boolean allowedForMinor) {
		super(name);
		this.allowedForMinor = allowedForMinor;
	}
	public boolean isAllowedForMinor() {
		return allowedForMinor;
	}
}
```

Target classes:
```java
public abstract class VehicleDto {
	private final String name;
	public VehicleDto(String name) {
		this.name = name;
	}
}

public class CarDto extends VehicleDto {
	private final int numOfDoors;
	public CarDto(String name, int numOfDoors) {
		super(name);
		this.numOfDoors = numOfDoors;
	}
}

public class MotorbikeDto extends VehicleDto {
	private final boolean allowedForMinor;
	public MotorbikeDto(String name, boolean allowedForMinor) {
		super(name);
		this.allowedForMinor = allowedForMinor;
	}
}
```

Mapper config:
```java
@Mapper(subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface VehicleMapper {
	@SubclassMapping(target = CarDto.class, source = Car.class)
	@SubclassMapping(target = MotorbikeDto.class, source = Motorbike.class)
	VehicleDto mapToDto(Vehicle vehicle);
}
```

Everything works fine so far, the mapper class is generated and mapping correctly all the fields. 

1.
The problem occurs when I'm trying to add anything related to name field in VehicleDto, for example:
```java
@Mapper(subclassExhaustiveStrategy = SubclassExhaustiveStrategy.RUNTIME_EXCEPTION)
public interface VehicleMapper {
	@SubclassMapping(target = CarDto.class, source = Car.class)
	@SubclassMapping(target = MotorbikeDto.class, source = Motorbike.class)
	@Mapping(target = "name", constant = "noname") // <-------- added this one --------
	VehicleDto mapToDto(Vehicle vehicle);
}
```

In this case I'm getting a compilation error:
>Unknown property "name" in result type VehicleDto. Did you mean "null"?

2.
If I also add getter to the abstract target class:
```java
public abstract class VehicleDto {
	private final String name;
	public VehicleDto(String name) {
		this.name = name;
	}
	public String getName() {
		return name;
	}
}
```
It's still not working but the build error is different:
>Property "name" has no write accessor in VehicleDto.

Isn't Mapstruct supposed to handle both these cases correctly and map the name field?

I'm using Java 17, Spring Boot 3.1.1, no Lombok.

### MapStruct Version

1.5.5.Final

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #3331

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java [hunk 1]
```diff
@@ -284,10 +284,16 @@ else if ( !method.isUpdateMethod() ) {
...
 
-            // map properties with mapping
-            boolean mappingErrorOccurred = handleDefinedMappings( resultTypeToMap );
-            if ( mappingErrorOccurred ) {
-                return null;
+            boolean hasSubclassMappingsWithAllSupportedClasses = hasSubclassMappingsWithAllSupportedClasses(
+                resultTypeToMap );
+
+
+            if ( hasSubclassMappingsWithAllSupportedClasses ) {
```
Comment (thunderhook) [inline processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java:291]: Maybe there is another way to check if the `SubclassExhaustiveStrategy.RUNTIME_EXCEPTION` option is set? Maybe via `isAbstractReturnTypeAllowed()`?

I mean, perhaps this method should only be called, when the `SubclassExhaustiveStrategy.RUNTIME_EXCEPTION` is set, and not in every bean mapping method? This could have side effects in future code changes.

e.g.:
```java
if ( isRuntimeExceptionSubclassExhaustiveStrategy
     && hasSubclassMappingsWithAllSupportedClasses(...) ) {
  // ...
}
```

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java:291]: You are right. It didn't quite feel right to use this naming. I'll think of a better solution for this

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java]: I've renamed this. Is it clearer now?

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/BeanMappingMethod.java]: Going back a bit through some of the issues and my commits, I realized why I named it like I did. I am using that in https://github.com/filiphr/mapstruct/commit/d5cc43a19552967c7c682b9a1daec994a771445d which is a fix for #3360. @thunderhook do you think that the new local variable name is clear for that other commit as well?

**Comment by thunderhook** [comment]
Looks good to me. Thanks for renaming the variable.
