### PR TITLE
#2236 Different nested target mappings should generate different intermediate methods

### LINKED ISSUE #2236: Mapstruct started generating diffrent classes with issues after upgrade from 1.3.1.Final to 1.4.1.Final
Hi,

We are using  MapStruct But after upgrade from 1.3.1.Final to 1.4.1.Final, generated classes have issues.
It would be very helpful for us if you could let us know if this is considered a bug or not.
Looking forward to your feedback!

Here is an example.

Source Class:
```
package example.model.source;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Vehicle {
    CarDto carDto;
    String type;
}

```
```
package example.model.source;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CarDto {

    private String name;
    private String ownerNameA;
    private String ownerNameB;
    private String ownerCityA;
    private String ownerCityB;
}
```

Target Class:

```
package example.model.target;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Car {
    private String name;
    private String type;
    private Owner ownerA;
    private Owner ownerB;
}
```

```
package example.model.target;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Owner {

    String name;
    String city;
}
```

Mapper:
```

package example.mapper;

import example.model.target.Car;
import example.model.source.Vehicle;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
public interface CarMapper {

    @Mapping(target = "ownerA.name", source = "carDto.ownerNameA")
    @Mapping(target = "ownerA.city", source = "carDto.ownerCityA")
    @Mapping(target = "ownerB.name", source = "carDto.ownerNameB")
    @Mapping(target = "ownerB.city", source = "carDto.ownerCityB")
    @Mapping(target = "name", source = "carDto.name")
    @Mapping(target = "type", source = "type")
    Car VehicleToCar(Vehicle vehicle);
}
```

MapStruct version: 1.3.1.FINAL generates this mapper(Correct one):

```
package example.model.mapper;

import example.model.source.CarDto;
import example.model.source.Vehicle;
import example.model.target.Car;
import example.model.target.Owner;
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    comments = "version: 1.3.1.Final, compiler: javac, environment: Java 1.8.0_191 (Oracle Corporation)"
)
public class CarMapperImpl implements CarMapper {

    @Override
    public Car VehicleToCar(Vehicle vehicle) {
        if ( vehicle == null ) {
            return null;
        }

        Car car = new Car();

        car.setOwnerB( carDtoToOwner( vehicle.getCarDto() ) );
        car.setOwnerA( carDtoToOwner1( vehicle.getCarDto() ) );
        car.setName( vehicleCarDtoName( vehicle ) );
        car.setType( vehicle.getType() );

        return car;
    }

    protected Owner carDtoToOwner(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        Owner owner = new Owner();

        owner.setCity( carDto.getOwnerCityB() );
        owner.setName( carDto.getOwnerNameB() );

        return owner;
    }

    protected Owner carDtoToOwner1(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        Owner owner = new Owner();

        owner.setName( carDto.getOwnerNameA() );
        owner.setCity( carDto.getOwnerCityA() );

        return owner;
    }

    private String vehicleCarDtoName(Vehicle vehicle) {
        if ( vehicle == null ) {
            return null;
        }
        CarDto carDto = vehicle.getCarDto();
        if ( carDto == null ) {
            return null;
        }
        String name = carDto.getName();
        if ( name == null ) {
            return null;
        }
        return name;
    }
}
```

MapStruct version: 1.4.1.FINAL generates this mapper(Wrong One):

```
package example.model.mapper;

import example.model.source.CarDto;
import example.model.source.Vehicle;
import example.model.target.Car;
import example.model.target.Owner;
import javax.annotation.Generated;

@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2020-10-16T00:31:04+0200",
    comments = "version: 1.4.1.Final, compiler: javac, environment: Java 1.8.0_191 (Oracle Corporation)"
)
public class CarMapperImpl implements CarMapper {

    @Override
    public Car VehicleToCar(Vehicle vehicle) {
        if ( vehicle == null ) {
            return null;
        }

        Car car = new Car();

        car.setOwnerA( carDtoToOwner( vehicle.getCarDto() ) );
        car.setOwnerB( carDtoToOwner( vehicle.getCarDto() ) );
        car.setName( vehicleCarDtoName( vehicle ) );
        car.setType( vehicle.getType() );

        return car;
    }

    protected Owner carDtoToOwner(CarDto carDto) {
        if ( carDto == null ) {
            return null;
        }

        Owner owner = new Owner();

        owner.setName( carDto.getOwnerNameA() );
        owner.setCity( carDto.getOwnerCityA() );

        return owner;
    }

    private String vehicleCarDtoName(Vehicle vehicle) {
        if ( vehicle == null ) {
            return null;
        }
        CarDto carDto = vehicle.getCarDto();
        if ( carDto == null ) {
            return null;
        }
        String name = carDto.getName();
        if ( name == null ) {
            return null;
        }
        return name;
    }
}
```

Here , with mapstruct version 1.4.1.Final , generated classes have same carDtoToOwner for both OwnerA and OwnerB, which is assigning same values carDto OwnerNameA and OwnerCityA to both Car OwnerA and OwnerB. 
Although, this beaviour was fine in 1.3.1.Final.

### PR DESCRIPTION
**Pull request by filiphr**
Make sure that MappingReferences are taken into consideration when comparing whether 2 mapping methods are equal.
This makes sure that when using nested target mappings that have the same property mappings, but different mappings 2 distinct methods will be created

Fixes #2236 

In 1.3.1.Final this worked by accident because the property mappings in the `BeanMappingMethod` were in a different order. However, we should take the mapping references that were used to construct the method when comparing whether 2 methods are equals.

### CODE REVIEW

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Issue2236Test.java [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    public void shouldCorrectlyMapSameTypesWithDifferentNestedMappings() {
+
+        Vehicle vehicle = new Vehicle();
+        vehicle.setType( "Sedan" );
+        CarDto carDto = new CarDto();
+        vehicle.setCarDto( carDto );
+
+        carDto.setName( "Private car" );
+        carDto.setOwnerNameA( "Owner A" );
+        carDto.setOwnerCityA( "Zurich" );
```
Comment (sjaakd) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Issue2236Test.java:40]: autobiographic?

**Review by sjaakd — APPROVED** [review]

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Issue2236Test.java (hunk 1 above)
Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_2236/Issue2236Test.java:40]: Only the city, nothing else ;)

**Comment by filiphr** [comment]
Thanks for the review @sjaakd
