### PR TITLE
#2839 keep thrown types when creating a new ForgedMethod with the same arguments

### LINKED ISSUE #2839: Compilation error when mapping fields with the same type due to not wrapping in a `try-catch` block
The mapper for the following class cannot be generated:

```java
...
public final class FinancingProductDto {
  ...
  private final List<CommitmentFeeDto> conditionedCommitmentFees;
  private final List<CommitmentFeeDto> unconditionedCommitmentFees;
...
```

The second mapped field is not wrapped in a `try-catch` block:

```java
...
        try {
            conditionedCommitmentFees = commitmentFeeDtoListToCommitmentFeeList( dto.getConditionedCommitmentFees() );
        }
        catch ( IllegalAccessException e ) {
            throw new RuntimeException( e );
        }
        catch ( InvocationTargetException e ) {
            throw new RuntimeException( e );
        }
        catch ( InstantiationException e ) {
            throw new RuntimeException( e );
        }
        catch ( NoSuchMethodException e ) {
            throw new RuntimeException( e );
        }
        unconditionedCommitmentFees = commitmentFeeDtoListToCommitmentFeeList( dto.getUnconditionedCommitmentFees() );
...
```

The following error is occurring: `unreported exception java.lang.IllegalAccessException; must be caught or declared to be thrown`

Here is an example project to reproduce the issue: https://github.com/hakan0xFF/mapstruct-mapping-issue

The error occurs also with the latest stable version `1.4.2.Final`.

### PR DESCRIPTION
**Pull request by hakan0xFF**
fixes #2839

### CODE REVIEW

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+public abstract class CarMapper {
+
+    public static final CarMapper MAPPER = Mappers.getMapper( CarMapper.class );
+
+    public abstract Car toEntity(CarDto dto);
+
+    public abstract CarDto toDto(Car entity);
+
+    protected Id mapId(UUID id) throws InstantiationException {
+        return id != null ? new Id( id ) : null;
```
Comment (sjaakd) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java:26]: It would be nice to actually trigger the exception based on the data and verify that scenario in your test.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    }
+
+    protected UUID mapId(Id id) throws NoSuchMethodException {
+        return id != null ? id.getId() : null;
```
Comment (sjaakd) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java:30]: It would be be nice to trigger the exception based on the data and verify that.

**Review by sjaakd — CHANGES_REQUESTED** [review]

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java (hunk 1 above)
Comment (hakan0xFF) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java]: Done. Thx for the feedback.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java (hunk 2 above)
Comment (hakan0xFF) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java:32]: I've removed `throws` from this method as it's not needed here.

Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java:32]: It is not only for removing the `throws`. I think what @sjaakd wanted to see was to throw an exception in one of these methods and verify that in the tests.

Comment (hakan0xFF) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_2839/CarMapper.java]: Oh, I see. Done, the exceptions are thrown now. One additional thing that I noticed is that checked exceptions are failing however unchecked exceptions are just fine.

**Comment by filiphr** [comment]
@hakan0xFF I've applied the requested changes by @sjaakd to your branch and pushed it. Once the tests are green I am going to merge this PR. Thanks for your work on it.
