### PR TITLE
#3591 Potential fix for duplicate methods generated.

### LINKED ISSUE #3591: Compilation Error - Duplicate Methods generated
### Expected behavior
No duplicated methods.

leads to following error: `method beanListToBeanDTOList(java.util.List<Bean>) is already defined`

### Actual behavior

```java
public class BeanMapperImpl implements BeanMapper {
    @Override
    public BeanDTO map(Bean source, BeanDTO target) {
        if ( source == null ) { return target; }
        if ( target.getBeans() != null ) {
            List<BeanDTO> list = beanListToBeanDTOList( source.getBeans() );
            if ( list != null ) {
                target.getBeans().clear();
                target.getBeans().addAll( list );
            } else { target.setBeans( null ); }
        } else {
            List<BeanDTO> list = beanListToBeanDTOList( source.getBeans() );
            if ( list != null ) { target.setBeans( list ); }
        }
        return target;
    }
    protected List<BeanDTO> beanListToBeanDTOList(List<Bean> list) {
        if ( list == null ) { return null; }
        List<BeanDTO> list1 = new ArrayList<BeanDTO>( list.size() );
        for ( Bean bean : list ) { list1.add( beanToBeanDTO( bean ) ); }
        return list1;
    }
    protected BeanDTO beanToBeanDTO(Bean bean) {
        if ( bean == null ) { return null; }
        BeanDTO beanDTO = new BeanDTO();
        beanDTO.setBeans( beanListToBeanDTOList( bean.getBeans() ) );
        return beanDTO;
    }
    protected List<BeanDTO> beanListToBeanDTOList(List<Bean> list) {
        if ( list == null ) { return null; }
        List<BeanDTO> list1 = new ArrayList<BeanDTO>( list.size() );
        for ( Bean bean : list ) { list1.add( beanToBeanDTO( bean ) ); }
        return list1;
    }
}
``` 

### Steps to reproduce the problem

SourceFiles to reproduce:
```java
public class Bean {
    private List<Bean> beans;
    public List<Bean> getBeans() { return beans; }
    public void setBeans(List<Bean> beans) { this.beans = beans; }
}
``` 
```java
public class BeanDTO {
    private List<BeanDTO> beans;
    public List<BeanDTO> getBeans() { return beans; }
    public void setBeans(List<BeanDTO> beans) { this.beans = beans; }
}
``` 
```java
@Mapper
public interface BeanMapper {
    BeanMapper INSTANCE = Mappers.getMapper(BeanMapper.class);
    @Mapping(source = "beans", target = "beans")
    BeanDTO map(Bean source, @MappingTarget BeanDTO target);
}
``` 

### MapStruct Version

1.5.5.Final

### PR DESCRIPTION
**Pull request by Hypnagokali**
Fixes #3591

I am not sure if my solution is an acceptable one, but it solves this bug for now.
**Problem**: There were two methods generated and both are written to the mapper class because the selectionParameters in the ContainerMappingMethods are not equal and therefore the methods are not equal and finally both are used.
- The defined mapping has an empty instance of SelectionParameters (returned from MappingOptions)
- The generated mapping has null for selectionParameters.

**Solution**: MappingOption now returns null for selectionParameters if no values have been set.

I am still confused why two methods of beanListToBeanDtoList are forged at all. I would like to take another look at this.

### CODE REVIEW

**Comment by zyberzebra** [comment]
> I am not sure if my solution is an acceptable one, but it solves this bug for now. **Problem**: There were two methods generated and both are written to the mapper class because the selectionParameters in the ContainerMappingMethods are not equal and therefore the methods are not equal and finally both are used.
 Good Catch, the question is now what leads to this behaviour? And is your provided solution just a workaround/bandaid for the actual problem. But I tried your solution and it works. 
 I'm also gonna try and have look what causes this.
 
 Maybe it's something caused by the recursive nature here? 
 Bean#Beans#Bean#Beans#......
 And maybe it would generate even more duplicate methods, but it stops before that because of the first duplicate error

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java [hunk 1]
```diff
@@ -421,7 +421,7 @@ public FormattingParameters getFormattingParameters() {
     }
 
     public SelectionParameters getSelectionParameters() {
-        return selectionParameters;
+        return selectionParameters.isEmpty() ? null : selectionParameters;
```
Comment (zyberzebra) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java:424]: Is it "safe" to just return null here?

**Comment by Hypnagokali** [comment]
> Maybe it's something caused by the recursive nature here? Bean#Beans#Bean#Beans#...... And maybe it would generate even more duplicate methods, but it stops before that because of the first duplicate error

Thanks for the feedback. Yes, the recursive structure of the bean must be the cause, but the MapperCreationProcess ends "successfully" and the duplication error only becomes visible during compilation. At some point, the mapper decides not to create any more methods although the equals method fails.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java (hunk 1 above)
Comment (Hypnagokali) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java:424]: This is no longer necessary, I will remove it with the next commit.

**Comment by Hypnagokali** [comment]
I have added a test for StreamMapping and MapMapping.
It works, but actually both mapping methods are generated twice. However, finally only one method is added to `MappingBuilderContext#mappingsToGenerate`, because their equals methods do not depend on `selectionParameters`.

Should I fix this behaviour even though it does not lead to an error?
I would then implement a `createOrGetForgedAssignment` method in `AbstractBaseBuilder` that checks if there is a forged method under creation.

**Comment by Hypnagokali** [comment]
Okay, everything should be done now. I hope I haven't missed anything.

I still have a question:
All workflow jobs fail with: "Some files do not have the expected license header", what does that mean?

**Comment by thunderhook** [comment]
> Okay, everything should be done now. I hope I haven't missed anything.
> 
> I still have a question: All workflow jobs fail with: "Some files do not have the expected license header", what does that mean?

This is a check if every file contains the copyright header at the first lines:
```
/*
 * Copyright MapStruct Authors.
 *
 * Licensed under the Apache License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
 */
```

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+        assertThat( dto.getBeanMap() ).isNotEmpty();
+        assertThat( dto.getBeanMap().get( "child" ).getValue() ).isEqualTo( "mapChild" );
+
+        List<ContainerBeanDto> fromStream = dto.getBeanStream().collect( Collectors.toList() );
+        assertThat( fromStream ).isNotEmpty();
+        assertThat( fromStream.get( 0 ).getValue() ).isEqualTo( "streamChild" );
+    }
+
+    static ContainerBean testContainerBean() {
```
Comment (zyberzebra) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java:74]: Should these helper methods really be own methods? They are only used 1 time in their respective tests.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+        generatedSource.addComparisonToFixtureFor( ContainerBeanMapper.class );
+    }
+
+    @ProcessorTest
+    @WithClasses({
+        ContainerBean.class,
+        ContainerBeanDto.class,
+        ContainerBeanMapper.class,
+    })
+    void shouldMapNestedMapAndStream() {
```
Comment (zyberzebra) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java:61]: Inlined and with some assertJ features: 
```java
    void shouldMapNestedMapAndStream() {
        ContainerBean containerBean = new ContainerBean( "parent" );
        containerBean.setBeanMap( Map.of( "child", new ContainerBean( "mapChild" ) ) );

        ContainerBean streamChild = new ContainerBean( "streamChild" );
        containerBean.setBeanStream( Stream.of( streamChild ) );

        ContainerBeanDto dto = ContainerBeanMapper.INSTANCE.mapWithMapMapping( containerBean, new ContainerBeanDto() );

        assertThat( dto.getBeanMap() )
            .extractingByKey( "child" )
            .extracting( ContainerBeanDto::getValue )
            .isEqualTo( "mapChild" );

        assertThat( dto.getBeanStream() )
            .singleElement()
            .extracting( ContainerBeanDto::getValue )
            .isEqualTo( "streamChild" );
    }
``` 
Maybe you see something you like :)

**Comment by zyberzebra** [comment]
It's working! Pretty cool! :) Lets see what the maintainers have to say

File: processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java [hunk 4]
```diff
@@ -121,7 +140,7 @@ Assignment createForgedAssignment(SourceRHS source, ForgedMethod methodRef, Mapp
         return createAssignment( source, methodRef );
     }
 
-    private Assignment createAssignment(SourceRHS source, ForgedMethod methodRef) {
+    Assignment createAssignment(SourceRHS source, ForgedMethod methodRef) {
```
[the remark this answers is not in the document]
Comment (Hypnagokali) [reply processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java]: You are right. Just a relic from my second draft. I have fixed that.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java (hunk 3 above)
Comment (Hypnagokali) [reply processor/src/test/java/org/mapstruct/ap/test/bugs/_3591/CompilationErrorDuplicateMethodsBugTest.java:60]: That is much better and more readable. Thanks 👍

File: processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java [hunk 5]
```diff
@@ -46,7 +46,14 @@ public abstract class ContainerMappingMethod extends NormalTypeMappingMethod {
             afterMappingReferences );
         this.elementAssignment = parameterAssignment;
         this.loopVariableName = loopVariableName;
-        this.selectionParameters = selectionParameters;
+
+        if ( selectionParameters == null ) {
+            this.selectionParameters = SelectionParameters.forSourceRHS( null );
```
[the remark this answers is not in the document]
Comment (Hypnagokali) [reply processor/src/main/java/org/mapstruct/ap/internal/model/ContainerMappingMethod.java]: You are right - it could be confusing. I have changed that to `SelectionParameters.emptyInstance()`

**Comment by zyberzebra** [comment]
Is this Issue related? https://github.com/mapstruct/mapstruct/issues/3532

**Comment by filiphr** [comment]
Nice work @Hypnagokali and @zyberzebra. Good catch with the `null` and empty `SelectionParameters`.

I pushed one small polish commit. I'll merge this once the build is done

**Comment by filiphr** [comment]
And you are right @zyberzebra #3532 does look identical to this one. I'll close it out
