### PR TITLE
#1102 Add support for Auto forging of Enum properties

### LINKED ISSUE #1102: 1.2.0-Beta1 Automapping Feature: doesn't work with enums
enums are not Mapped (Error "Consider to declare/implement a mapping method: ..."):
[MapStructEnumMapper.java.txt](https://github.com/mapstruct/mapstruct/files/801846/MapStructEnumMapper.java.txt)

The Docu "mapstruct-reference-guide.asciidoc" says:

	MapStruct will only create a new mapping method if and only if the source and target property
	are  properties of a Bean and they themselves are Beans or simple properties.
	i.e. they are not Collection or Map type properties.

Maybe enums doesn't fall under "simple properties"?

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #1102 

Maybe we need to do the same that it is done in `MapperCreationProccessor.getMappingMethods()`

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java [hunk 1]
```diff
@@ -381,9 +381,7 @@ public boolean isMapMapping() {
 
     public boolean isEnumMapping() {
         if ( isEnumMapping == null ) {
-            isEnumMapping = getSourceParameters().size() == 1
-                && first( getSourceParameters() ).getType().isEnumType()
-                && getResultType().isEnumType();
+            isEnumMapping = MappingMethodUtils.isEnumMapping( this );
```
Comment (gunnarmorling) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java]: What's the motivation for extracting the static helper method?

File: processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+
+        List<org.mapstruct.ap.test.nestedbeans.other.WheelDto> list1 = new ArrayList<org.mapstruct.ap.test.nestedbeans.other.WheelDto>();
+        for ( Wheel wheel : list ) {
+            list1.add( wheelToWheelDto1( wheel ) );
+        }
+
+        return list1;
+    }
+
+    protected org.mapstruct.ap.test.nestedbeans.other.CarDto carToCarDto1(Car car) {
```
Comment (gunnarmorling) [inline processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java]: Any idea why we don't import `CarDto` here? Probably unrelated to the issue at bay, so could you open an issue for keeping track of it?

File: processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java [hunk 3]
```diff
@@ -41,6 +44,13 @@
 @RunWith(AnnotationProcessorTestRunner.class)
 public class NestedSimpleBeansMappingTest {
 
+    @Rule
+    public final GeneratedSource generatedSource = new GeneratedSource().addComparisonToFixtureFor(
```
Comment (gunnarmorling) [inline processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java]: There doesn't seem to be an actual test for the generated functionality? Having the assertion on the generated source is great, but there should be a test the actual functionality, too.

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java (hunk 1 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java]: Because I also need it in the `AbstractBaseBuilder` line 61. In the method `createForgedBeanAssignment`, which I should probable rename to `createForgedAssignment` now. 

I would have extracted the method to a `default` on the `Method`, but no Java 8 for us yet :).

What is your suggestion for reusing the logic?

File: processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java (hunk 3 above)
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java]: What do you mean? That I don't call the `getter` and check if they are actually what we expect? This tests for this actually work with the overridden `equals` on the Dtos. I can change the assertions to actually call the `getters` instead

File: processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java (hunk 2 above)
Comment (filiphr) [inline processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java]: There are `CarDto` from 2 different packages in here that's why. Those were added to make sure that we are going to generate the method names accordingly.

There is no import for the second CarDto because it is in the same package as the mapper.

**Comment by filiphr** [comment]
@gunnarmorling thanks for the comments. I replied to them inline.

Regarding your question for `@ValueMapping`. With the current implementation it will only work if the source type can be mapped automatically to the target, i.e. the source enum is a subset of the target. 

I see 2 possibilities for dealing with different source and target types:
* If we implement #1086 then the users will have to define it in those prototypes
* Extend the `@ValueMapping` with a `sourceClass` and `targetClass`. Then those should then be filtered and passed down to the forged methods accordingly.

File: processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java [hunk 4]
```diff
@@ -55,11 +56,21 @@ public B method(Method sourceMethod) {
      *
      * @return See above
      */
-    Assignment createForgedBeanAssignment(SourceRHS sourceRHS, ForgedMethod forgedMethod) {
-        BeanMappingMethod forgedMappingMethod = new BeanMappingMethod.Builder()
-            .forgedMethod( forgedMethod )
-            .mappingContext( ctx )
-            .build();
+    Assignment createForgedAssignment(SourceRHS sourceRHS, ForgedMethod forgedMethod) {
```
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java]: I renamed the method to match it's new functionality. Is it misleading that we have 2 method with the same name, but different parameters?

File: processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java [hunk 5]
```diff
@@ -73,7 +73,7 @@ Assignment forgeMapping(SourceRHS sourceRHS, Type sourceType, Type targetType) {
             true
         );
 
-        return createForgedBeanAssignment( sourceRHS, forgedMethod );
+        return createForgedAssignment( sourceRHS, forgedMethod );
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java]: Hey guys.. I was thinking. Should forging not be part of the selector or `MappingResolverImpl`? So, if you cannot select something else.. Just forge a method. Then it would solve it not only for `BeanMapping`, but also `IterableMapping` en `MapMapping`..

Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/AbstractMappingMethodBuilder.java]: I was thinking the same @sjaakd. That is what I meant with:
>Maybe we need to do the same that it is done in MapperCreationProccessor.getMappingMethods()

If you all agree, I can theoretically do it as part of this PR, or you prefer a new issue?

**Comment by sjaakd** [comment]
I would do it in a separate pr! I issued a new issue earlier today handling list-of-lists. Perhaps it lends itself better for tackling this one..

File: processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java (hunk 2 above)
Comment (gunnarmorling) [inline processor/src/test/resources/fixtures/org/mapstruct/ap/test/nestedbeans/UserDtoMapperSmartImpl.java]: Ah yes, makes sense. I was surprised by such apparent issue, so it's good to know it actually all is good :)

File: processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java (hunk 3 above)
Comment (gunnarmorling) [inline processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java]: Yes, I would have expected a test which accesses the state of the target object.

**Comment by gunnarmorling** [comment]
> With the current implementation it will only work if the source type can be mapped automatically to the target, i.e. the source enum is a subset of the target.

Ok, that makes sense. If that's not doable, an error should be raised, suggesting to create a mapping method for the enum types.

> Extend the @ValueMapping with a sourceClass and targetClass.

I'd rather have people implement a proper enum mapping method, hinted by an error message as described above.

File: processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java (hunk 4 above)
Comment (gunnarmorling) [inline processor/src/main/java/org/mapstruct/ap/internal/model/AbstractBaseBuilder.java]: Seems alright to me :)

File: processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java (hunk 3 above)
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/nestedbeans/NestedSimpleBeansMappingTest.java]: @gunnarmorling with my latest commit the state of the target object is accessed and asserted

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java (hunk 1 above)
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/SourceMethod.java]: @gunnarmorling you didn't get back to me about this one.

**Comment by filiphr** [comment]
@gunnarmorling, @sjaakd I updated the PR to access the state of the target object when asserting. I also adapted the `Message.VALUE_MAPPING_UNMAPPED_SOURCES` to display the path of the property when there is a history.

Let me know what you think about the latest changes.

If someone else is merging this, I am completely OK (and I would prefer) to squash everything into one commit
