### PR TITLE
#725 Flag the Annotation element with the wrong dateFormat

### LINKED ISSUE #725: Validate value given for date format is valid

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #725 

I wanted to add the column number to our diagnostics. However, that does not work correctly :). 

* The eclipse compiler finds out the column. However, it is never used :). There might be a bug report, but I can't find it. I just looked at their sources
* As for javac it will work in JDK 9, see [JDK-6388543](https://bugs.openjdk.java.net/browse/JDK-6388543)

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/common/HasFormattingParameters.java [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+import javax.lang.model.element.AnnotationMirror;
+import javax.lang.model.element.AnnotationValue;
+import javax.lang.model.element.Element;
+
+/**
+ * Formatting parameters for the common subpackage.
+ *
+ * @author Filip Hrisafov
+ */
+public interface HasFormattingParameters {
```
Comment (agudian) [inline processor/src/main/java/org/mapstruct/ap/internal/model/common/HasFormattingParameters.java]: I don't quite get why we need this interface... Do we need one in the common package? Could we also just move `FormattingParameters` to the common package? My main concern is that `HasFormattingParameters` reads a bit funny and I guess it's hard to come up with a better name... 🙄

Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/common/HasFormattingParameters.java]: We actually don't, moving the `FormattingParameters` to the `common` package works. I'll do that. I did it due to some package cycle problems.

**Comment by filiphr** [comment]
Thanks for the review @agudian
