### PR TITLE
#2169 Add support for defining a custom default exception for enum mapping

### LINKED ISSUE #2169: customize thrown Exception when Enum Mapping fails
It would be nice to be able to configure the Mapper to throw a custom Exception for an unknown enum value, instead of an `IllegalArgumentException`.

Possible solution:
@filiphr:
> We've added EnumNamingStrategy in 1.4. Perhaps we can rename that to EnumMapingStrategy and add a method that would return the TypeElement of the exception that it should be thrown.

For now we manipulated `ValueMappingMethod.ftl` in the classpath, but this is an internal file, hence not the way to go: mapstruct might switch away from using freemarker templates in the near future.

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #2169

Perhaps we should rename `EnumNamingStrategy` into `EnumMappingStrategy`. Not sure if naming is still correct if we have the `getDefaultExceptionType()` in there.

What do you think @sjaakd

### CODE REVIEW

**Comment by sjaakd** [comment]
I guess the latter feels better..

**Comment by filiphr** [comment]
>Does enummapping inherit from mapper? Iiuc you'll have to apply this for each method right? (Cannot see the full context from a mobile)

If you mean whether you can define the default exception on a `@Mapper` level or `@MapperConfig`. Then the answer is no. Should we expose it? It is exposed as an SPI globally

**Comment by sjaakd** [comment]
I think we should. I thought we used the SPI for standard post and prefix stuff and the SPI for more tricky things.. that makes sense. But an exception and the standard stuff should follow the same rules as other settings. I'd prefer the SPI not to see as a 'straightforward' interface but to reserve it's use only for 'team' or 'organisation' policy stuff or for stuff that's too complex in doing otherwise like programmatic manipulation

**Comment by sjaakd** [comment]
Does the new interface add checked exceptions to the signature of the value mapping method?

**Comment by sjaakd** [comment]
Are exception  imports handled correctly?

**Comment by sjaakd** [comment]
What about exceptions with a non empty constructor?

**Comment by filiphr** [comment]
I haven't answered your questions it seems @sjaakd.

>I think we should. I thought we used the SPI for standard post and prefix stuff and the SPI for more tricky things.. that makes sense. But an exception and the standard stuff should follow the same rules as other settings. I'd prefer the SPI not to see as a 'straightforward' interface but to reserve it's use only for 'team' or 'organisation' policy stuff or for stuff that's too complex in doing otherwise like programmatic manipulation

I agree, we should expose this setting on `@Mapper` and `@MapeprConfig` as well.

>Does the new interface add checked exceptions to the signature of the value mapping method?

Not entirely following. We can't add a new checked exception to an overridden method.

>Are exception imports handled correctly?
Yes they are, have a look at the test fixture `CustomDefaultExceptionMapperImpl.java`.

>What about exceptions with a non empty constructor?

I was not sure about this one. We can do that check, and tell the user that we require the exception to have a constructor that takes a `String` for the message or we can leave it to the compilation. The generated code will not compile anyways.

**Comment by sjaakd** [comment]
> I was not sure about this one. We can do that check, and tell the user that we require the exception to have a constructor that takes a `String` for the message or we can leave it to the compilation. The generated code will not compile anyways.

That's true.. And, perhaps.. using an `ObjectFactory` in these cases makes more sense...

**Comment by filiphr** [comment]
>And, perhaps.. using an `ObjectFactory` in these cases makes more sense...

An `ObjectFactory` for creating an instance of the Exception? I would prefer to avoid that complexity.

File: processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java [hunk 1]
```diff
@@ -485,16 +500,28 @@ String getValue(ValueMappingOptions valueMapping) {
     }
 
     private ValueMappingMethod(Method method, List<MappingEntry> enumMappings, String nullTarget, String defaultTarget,
-        boolean throwIllegalArgumentException, List<LifecycleCallbackMethodReference> beforeMappingMethods,
+        Type defaultException,
+        List<LifecycleCallbackMethodReference> beforeMappingMethods,
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java:504]: I know it is not part of this solution.. but I'm not happy with those methods coming from `@BeanMapping`.. I think they should be provided by `@EnumMapping`

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/ValueMappingMethod.java:504]: the selectors are coming from `BeanMapping` indeed. I think that this is a good think for the 2.0 API overhauling. perhaps the qualifiers should go in their own annotation for this.

File: processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/exception/CustomDefaultExceptionDefinedInMapperConfigImpl.java [hunk 2]
```diff
@@ -0,0 +1,101 @@
...
+            break;
+            case STANDARD: externalOrderType = ExternalOrderType.DEFAULT;
+            break;
+            case NORMAL: externalOrderType = ExternalOrderType.DEFAULT;
+            break;
+            case RETAIL: externalOrderType = ExternalOrderType.RETAIL;
+            break;
+            case B2B: externalOrderType = ExternalOrderType.B2B;
+            break;
+            default: throw new CustomIllegalArgumentException( "Unexpected enum constant: " + orderType );
```
Comment (sjaakd) [inline processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/exception/CustomDefaultExceptionDefinedInMapperConfigImpl.java:73]: when you throw a checked exception.. shouldn't we check whether the method signature has defined such exception in the throws clause or do we leave this up to the compiler?

File: core/src/main/java/org/mapstruct/EnumMapping.java [hunk 3]
```diff
@@ -111,13 +111,22 @@
...
      * The configuration that should be passed on the appropriate name transformation strategy.
      * e.g. a suffix that should be applied to the source enum when doing name based mapping.
      *
      * @return the configuration to use
      */
-    String configuration();
+    String configuration() default "";
+
+    /**
+     * Exception that should be thrown by the generated code if no mapping matches.
```
Comment (sjaakd) [inline core/src/main/java/org/mapstruct/EnumMapping.java:125]: we probably should mention that:
1. The exception should have an empty constructor
2. The exception (when checked) should be added to the method signature.

**Review by sjaakd — APPROVED** [review]
Still some minor comments.. I leave it up to you if it makes sense an how to handle those.. Otherwise LGTM

File: processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/exception/CustomDefaultExceptionDefinedInMapperConfigImpl.java (hunk 2 above)
Comment (filiphr) [reply processor/src/test/resources/fixtures/org/mapstruct/ap/test/value/exception/CustomDefaultExceptionDefinedInMapperConfigImpl.java:73]: I say we leave it to the compiler. In the end you as a user defines the exception that you want to throw, so it is entirely in your hands.

File: core/src/main/java/org/mapstruct/EnumMapping.java (hunk 3 above)
Comment (filiphr) [reply core/src/main/java/org/mapstruct/EnumMapping.java:125]: I'll add that.

Comment (sjaakd) [reply core/src/main/java/org/mapstruct/EnumMapping.java:125]: great.. After that, you could merge the PR..
