### PR TITLE
#2925 Fix IllegalArgumentException when resolving generic parameters

### LINKED ISSUE #2925: `Optional` wrapping pattern broken in 1.5.2.Final
I have an issue similar to #2673 in 1.5.2.Final.  Project to reproduce: https://github.com/facboy/mapstruct-bug

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/xyz/git/mapstruct-bug/src/main/java/org/facboy/mapstruct/OptionalBeanMapper.java:[6,16] error: Internal error in the mapping processor: java.lang.IllegalArgumentException: long     at jdk.compiler/com.sun.tools.javac.model.JavacTypes.getDeclaredType0(JavacTypes.java:272)     at jdk.compiler/com.sun.tools.javac.model.JavacTypes.getDeclaredType(JavacTypes.java:241)      at org.mapstruct.ap.internal.util.AbstractTypeUtilsDecorator.getDeclaredType(AbstractTypeUtilsDecorator.java:119)     at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.resolve(MethodMatcher.java:384)          at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.lineUp(MethodMatcher.java:173)         at org.mapstruct.ap.internal.model.source.MethodMatcher$GenericAnalyser.access$000(MethodMatcher.java:109)     at org.mapstruct.ap.internal.model.source.MethodMatcher.matches(MethodMatcher.java:70)         at org.mapstruct.ap.internal.model.source.SourceMethod.matches(SourceMethod.java:514)          at org.mapstruct.ap.internal.model.source.selector.TypeSelector.lambda$getMatchingParameterBinding$0(TypeSelector.java:164)    at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672)          at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660)         at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingParameterBinding(TypeSelector.java:163)     at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:77)       at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:67)        at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:485)         at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:230)         at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:169)          at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:145)          at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:256)      at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1412)        at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1376)        at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:294)          at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:418)     at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:181)     at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:135)       at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:82)        at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:350)        at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:330)        at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:279)          at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:174)        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1023)          at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:939)     at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1267)      at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1382)   at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1234)       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:916)    at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)   at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)  at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)   at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
[INFO] 1 error
```

### PR DESCRIPTION
**Pull request by filiphr**
When resolving the parameter for a method like:
```
<T> Optional<T> from(T value)
```

There was an exception in javac because getting a DeclaredType from an Optional
with a primitive type argument throws an exception.
Therefore, when assigning the type arguments we get the boxed equivalent.
This problem does not happen in the Eclipse compiler

Fixes #2925

### CODE REVIEW

**Comment by filiphr** [comment]
@sjaakd it would be good if you can have a look at this. This is in the area you worked on for the generics matching 😄

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java [hunk 1]
```diff
@@ -374,7 +374,7 @@ else if ( typeFromCandidateMethodTypeParameter.isWildCardBoundByTypeVar()
                             // something went wrong
                             return null;
                         }
-                        typeArgs[i] = matchingType.getTypeMirror();
+                        typeArgs[i] = matchingType.getBoxedEquivalent().getTypeMirror();
```
Comment (sjaakd) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java:377]: I guess this works because if this is not a boxed type it will return type. Perhaps add a comment here. And the javadoc on  `getBoxedEquivalent` should be adapted 😄

**Review by sjaakd — APPROVED** [review]
LGTM. However javadoc could be improved

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java (hunk 1 above)
Comment (sjaakd) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java:377]: Perhaps there are more occasions this situation arises. I believe that I somehow covered the scenario where the target is a generic parameter itself in the testcases. Lets just wait and see if more pop up.

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java:377]: The Javadoc says:

>Gets the boxed equivalent type if the type is primitive, int will return Integer

What more do you think I should add?

I'll add a comment on the line
