### PR TITLE
#2350 Generate core string to enum mapping when AnyRemaining or AnyUnmapped is not used

### LINKED ISSUE #2350: When using @ValueMapping string-to-enum mapping results in no cases in switch
My code:

```
@Mapper
public interface TransactionMapper {
    @Mapping(source = "fullName", target = "name")
    @Mapping(expression = "java(payload.getDonorFirstName() + \" \" + payload.getDonorLastName())", target = "donorName")
    @Mapping(source = "donorEmailAddress", target = "donorEmail")
    @Mapping(constant = "false", target = "processed")
    @Mapping(source = "schedule.givingFrequency", target = "recurringFrequency")
    @Mapping(source = "schedule.startDate", target = "recurringStartDate")
    @Mapping(source = "schedule.processImmediately", target = "processImmediately")
    TransactionEntity payloadToEntity(TransactionsPayload payload);

    @ValueMapping(source = "ONETIME", target = "ONE_TIME")
    TransactionType transactionTypeStringToTransactionType(String transactionTypeString);
}
```

The possible `String` values for `transactionTypeString` are `ONETIME`, `RECURRING` and `PLEDGE`. The `TransactionType` enum has values of `ONE_TIME`, `RECURRING` and `PLEDGE`. Not the underscore in `ONE_TIME`. That's why I have to specify the mapping.

The code generated has no `case` statements for each value and only the `default` that throws an exception:

```
@Override
    public TransactionType transactionTypeStringToTransactionType(String transactionTypeString) {
        if ( transactionTypeString == null ) {
            return null;
        }

        TransactionType transactionType;

        switch ( transactionTypeString ) {
            default: throw new IllegalArgumentException( "Unexpected enum constant: " + transactionTypeString );
        }
    }
```

If I change my mapper to:

```
@ValueMapping(source = "ONETIME", target = "ONE_TIME")
@ValueMapping( source = MappingConstants.ANY_REMAINING, target = "RECURRING" )
TransactionType transactionTypeStringToTransactionType(String transactionTypeString);
```

the generated code is:

```
@Override
    public TransactionType transactionTypeStringToTransactionType(String transactionTypeString) {
        if ( transactionTypeString == null ) {
            return null;
        }

        TransactionType transactionType;

        switch ( transactionTypeString ) {
            case "ONETIME": transactionType = TransactionType.ONE_TIME;
            break;
            case "ONE_TIME": transactionType = TransactionType.ONE_TIME;
            break;
            case "RECURRING": transactionType = TransactionType.RECURRING;
            break;
            case "PLEDGE": transactionType = TransactionType.PLEDGE;
            break;
            default: transactionType = TransactionType.RECURRING;
        }

        return transactionType;
    }
```

which is close. I need the `default` to still throw an exception.

### PR DESCRIPTION
**Pull request by filiphr**
Fixes #2350

### CODE REVIEW

File: processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java [hunk 1]
```diff
@@ -53,7 +54,20 @@ public void testRemainingAndNull() {
                     "type String to an enum type." )
         }
     )
-    public void shouldRaiseErrorWhenUsingAnyRemaining() {
+    public void shouldRaiseWarningWhenNotUsingAnyRemainingOrAnyUnmapped() {
```
Comment (sjaakd) [inline processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java:57]: Perhaps it is my misunderstanding.. Lets see if my assumption is correct:

* MapStruct will continue to do name based mapping for the remaining properties based on tartget
* And then still raise a warning (that cannot be suppressed)?

Or.. is this the default behavior and what should the user do to force MapStruct to continue with name-based mappings based on target without issuing a warning?

Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java:57]: Yes your assumptions are correct, this is what happens with this PR. Suppressing the warning could be done if we implement https://github.com/mapstruct/mapstruct/issues/2339.

Before, we generated a warning and didn't do name based mapping. This in my opinion is not correct and is misleading, since a warning should not stop the name based mapping.

Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java:57]: The warning possibly stems from the enum-to-enum mapping, where it totally makes sense and is in line with the normal `@Mapping` (when you miss targets). Here however, it feels a bit awkward. Perhaps we should advance #2339 as part of 1.5 to fully finish this one.

Comment (sjaakd) [reply processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java:57]: But than it has to be something like: `@ValueMapping(target = MappingConstants.THROW_EXCEPTION, source =  MappingConstants.ANY_UNMAPPED)` (all unmapped) and and `@ValueMapping(target = MappingConstants.THROW_EXCEPTION, source =  MappingConstants.ANY_UNY_REMAINING)` (all non-name-based unmapped)

Comment (filiphr) [reply processor/src/test/java/org/mapstruct/ap/test/value/string2enum/StringToEnumMappingTest.java:57]: I agree, and I also like #2339, so it will be part of 1.5 for sure :). Btw the `THROW_EXCEPTION` doesn't have to be only for the `ANY_UNMAPPED` or `ANY_REMAINING`, you can also define it for a specific mapping as well (although we need to see how the inverse works there (most likely it should be ignored).

**Review by sjaakd — APPROVED** [review]

**Comment by filiphr** [comment]
Thanks for the review @sjaakd
