### PR TITLE
#3652 Inverse Inheritance possible for ignore-mappings without source

### LINKED ISSUE #3652: Inverse Inheritance Strategy not working for ignored mappings only with target
### Expected behavior

Inverse Configuration is autmatically generated.

### Actual behavior

`@Mappings` have to be defined twice

### Setup
```java
@Mapper(config = FooBarConfig.class)
public interface FooBarMapper {

    Bar toBar(Foo foo);

    Foo toFoo(Bar bar);

}
@Data
class Foo { int secret; }
@Data
class Bar { int secret; }

@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG)
interface FooBarConfig {

    @Mapping(target = "secret", ignore = true)
    Bar toBar(Foo foo);

    @InheritInverseConfiguration(name = "toBar")
    Foo toFoo(Bar bar);
}
``` 

### Generated

```java
public class FooBarMapperImpl implements FooBarMapper {

    @Override
    public Bar toBar(Foo foo) {
        if ( foo == null ) {
            return null;
        }

        Bar bar = new Bar();

        return bar;
    }

    @Override
    public Foo toFoo(Bar bar) {
        if ( bar == null ) {
            return null;
        }

        Foo foo = new Foo();

        foo.setSecret( bar.getSecret() );

        return foo;
    }
}
``` 
### Only way to get it working
```java
@MapperConfig(mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_FROM_CONFIG)
interface FooBarConfig {
    @Mapping(target = "secret", ignore = true)
    Bar toBar(Foo foo);
    @Mapping(target = "secret", ignore = true)
    Foo toFoo(Bar bar);
}
``` 

### MapStruct Version

1.5.5

### PR DESCRIPTION
**Pull request by Hypnagokali**
Fixes #3652

I have added a test case where the target has a property that does not exist on the source type.
The inverse inheritation still works, because this property is then simply ignored in `BeanMappingMethod#handleDefinedMapping` (line 1240):

```java
else if ( inheritContext.isReversed() ) {
    // When a configuration is reverse inherited and there are no read or write accessor
    // then we should ignore this mapping.
    // This most likely means that we were mapping the source parameter to the target.
    // If the error is due to something else it will be reported on the original mapping
    return false;
}
```

I have another question:
The javadoc of `MappingOptions#canInverse` says:
>mapping can only be inversed if the source was not a constant nor an expression **nor a nested property**

But there is no check for a nested property in this method and it seems to work: Some tests uses `@InheritInverseConfiguration` with nested properties:
e.g.: `ReversingNestedSourcePropertiesConstructorTest#shouldGenerateNestedWithConfigReverse`

Should I remove this statement from the javadoc comment?

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java [hunk 1]
```diff
@@ -480,12 +480,11 @@ public MappingControl getMappingControl(ElementUtils elementUtils) {
 
     /**
      *  mapping can only be inversed if the source was not a constant nor an expression nor a nested property
-     *  and the mapping is not a 'target-source-ignore' mapping
```
Comment (zyberzebra) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java:483]: I'm still curious why this was explicitly stated here.

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java:483]: This looks like an ancient thing. The `MappingOptions` was called `Mapping` at some point. The rename was done in https://github.com/mapstruct/mapstruct/commit/7bee12138da5f601364987d053e4fd3eeb43cbcd.

The line `isIgnored && sourceName == null` was added first in https://github.com/mapstruct/mapstruct/commit/4d8bc29347e37bcf22d121829802e7f58603afbb. And looking at that commit it seems like the logic was not ported properly, because prior to that we had

```java
        // mapping can only be reversed if the source was not a constant nor an expression nor a nested property
        if ( constant != null || javaExpression != null ) {
            return null;
        }

        // should only ignore a property when 1) there is a sourceName defined or 2) there's a name match
        if ( isIgnored ) {
            if ( sourceName == null && !hasPropertyInReverseMethod( targetName, method ) ) {
                return null;
            }
        }
```

and after that we had

```java
        // mapping can only be reversed if the source was not a constant nor an expression nor a nested property
        // and the mapping is not a 'target-source-ignore' mapping
        if ( constant != null || javaExpression != null || ( isIgnored && sourceName == null ) ) {
            return null;
        }
```

I cannot say why this was the case back then

Comment (filiphr) [reply processor/src/main/java/org/mapstruct/ap/internal/model/source/MappingOptions.java:483]: I was curious too @zyberzebra. This looks like an ancient thing. The `MappingOptions` was called `Mapping` at some point. The rename was done in https://github.com/mapstruct/mapstruct/commit/7bee12138da5f601364987d053e4fd3eeb43cbcd.

The line `isIgnored && sourceName == null` was added first in https://github.com/mapstruct/mapstruct/commit/4d8bc29347e37bcf22d121829802e7f58603afbb. And looking at that commit it seems like the logic was not ported properly, because prior to that we had

```java
        // mapping can only be reversed if the source was not a constant nor an expression nor a nested property
        if ( constant != null || javaExpression != null ) {
            return null;
        }

        // should only ignore a property when 1) there is a sourceName defined or 2) there's a name match
        if ( isIgnored ) {
            if ( sourceName == null && !hasPropertyInReverseMethod( targetName, method ) ) {
                return null;
            }
        }
```

and after that we had

```java
        // mapping can only be reversed if the source was not a constant nor an expression nor a nested property
        // and the mapping is not a 'target-source-ignore' mapping
        if ( constant != null || javaExpression != null || ( isIgnored && sourceName == null ) ) {
            return null;
        }
```

Things were quite different back then. We are now handling the target later and differently to back then, so the fix done by @Hypnagokali looks like spot on.

**Comment by filiphr** [comment]
Thanks a lot for the quick fix @Hypnagokali. Nice spotting this.

>Should I remove this statement from the javadoc comment? 

Good catch @Hypnagokali. I think that we can remove the _nor a nested property_ statement from the Javadoc. We are clearly not doing that there 😄

**Comment by Hypnagokali** [comment]
All right, I have adjusted the comment :blush:
Thanks for reviewing @filiphr, @zyberzebra

**Comment by filiphr** [comment]
Thanks @Hypnagokali
