### PR TITLE
Add support for conditions on source parameters + fix incorrect use of source parameter in presence check method

### LINKED ISSUE #2610: Support conditional mapping for source parameters
With #2051 we added support for conditional mappings. Currently this only works for properties. However, it would be good to be able to apply the same logic for the source parameters.

e.g. If we have the following mapper

```java
@Mapper
public interface CarMapper {

    CarDto map(Car car);

}
```

We currently generated something like:

```java
public class CarMapperImpl implements CarMapper {

    public CarDto map(Car car) {
        if ( car == null ) {
            return null;
        }

        // perform mapping
    }
}
```

It would be good to be able to define a custom method that would tell is if the car should be mapped or not:

e.g. we could generate something like

```java
public class CarMapperImpl implements CarMapper {

    public CarDto map(Car car) {
        if ( isCarPresent(car) ) {
            return null;
        }

        // perform mapping
    }
}
```

where `isCarPresent` is a method on the `CarMapper`. It can be a method that is available anywhere in the same discovery mechanism we have for the property conditional methods.

I believe that this issue is not super difficult to implement and would appreciate if someone from the community is interested in stepping up.

### LINKED ISSUE #3270: @Condition badly implemented
### Expected behavior

@Condition should be a wrapper of the existing generated code (generated without this annotation). Not an overwritter of existing generated code.

### Actual behavior

When using @Condition, the generated code is rewritten which is bad (in comparison when not present). It needs to wrap it, not rewrite it.

### Steps to reproduce the problem

1) Create a classical mapper class : 

```
@Mapper(componentModel = "spring", uses = {TaxeMapper.class})
public interface FormuleMapper {

       Formule formuleEntityToDTO(FormuleOption formule);
}
```

2) Generated code : 

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2023-05-10T15:52:58+0200",
    comments = "version: 1.5.5.Final, compiler: javac, environment: Java 18.0.2.1 (Oracle Corporation)"
)
@Component
public class FormuleMapperImpl implements FormuleMapper {
@Override
    public Formule formuleEntityToDTO(FormuleOption formule) {
        if ( formule == null ) {
            return null;
        }

        Formule formule1 = new Formule();

        formule1.setId( formule.getId() );
        formule1.setNom( formule.getNom() );
        formule1.setCode( formule.getCode() );
        formule1.setOrdre( formule.getOrdre() );
        formule1.setCommentaire( formule.getCommentaire() );
        formule1.setFormuleAssemblage( formule.getFormuleAssemblage() );
        formule1.setProduit( produitToIdNom( formule.getProduit() ) );
        formule1.setTaxes( ligneTaxeSetToIdNomRepartitionList( formule.getTaxes() ) );
        formule1.setBrouillon( formule.isBrouillon() );
        formule1.setType( getTypeFormule( formule.getType() ) );
        if ( formule.getMinimumPrimeTechniquePure() != null ) {
            formule1.setMinimumPrimeTechniquePure( formule.getMinimumPrimeTechniquePure().doubleValue() );
        }
        return formule1;
    }
}
```

Steps above are OK. Now let's introduce @Condition with generated code to compare : 

1) 

```
@Mapper(componentModel = "spring", uses = {TaxeMapper.class})
public interface FormuleMapper {
  
    Formule formuleEntityToDTO(FormuleOption formule);

@Condition
    default boolean targetFormuleOptionNotNull(fr.cfdp.services.produit.model.entity.produit.FormuleOption targetFormuleOption) {
        return targetFormuleOption != null ;
    }
}
```

2)

```
@Override
    public Formule formuleEntityToDTO(FormuleOption formule) {
        if ( formule == null ) {
            return null;
        }

        Formule formule1 = new Formule();

        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setId( formule.getId() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setNom( formule.getNom() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setCode( formule.getCode() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setOrdre( formule.getOrdre() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setCommentaire( formule.getCommentaire() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setFormuleAssemblage( formule.getFormuleAssemblage() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setProduit( produitToIdNom( formule.getProduit() ) );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setTaxes( ligneTaxeSetToIdNomRepartitionList( formule.getTaxes() ) );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setBrouillon( formule.isBrouillon() );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setType( getTypeFormule( formule.getType() ) );
        }
        if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setMinimumPrimeTechniquePure( formule.getMinimumPrimeTechniquePure().doubleValue() );
        }
        return formule1;
    }
```

So can you explain this difference in generated code : 

```
if ( formule.getMinimumPrimeTechniquePure() != null ) {
            formule1.setMinimumPrimeTechniquePure( formule.getMinimumPrimeTechniquePure().doubleValue() );
        }
```

become : 

```
 if ( targetFormuleOptionNotNull( formule ) ) {
            formule1.setMinimumPrimeTechniquePure( formule.getMinimumPrimeTechniquePure().doubleValue() );
        }
```

Which ends with a NullPointerException in my unit tests.

Thanks for lookup source problem.

### MapStruct Version

1.5.5.Final

### LINKED ISSUE #3459: Method with `@Condition` acts strange when applying to source
### Expected behavior

when `@Condition` annotated method's parameter type is same to mapping source
```java
    DTO toDto(E entity);

    @Condition
    default boolean isEntityAvailable(E entity) {
        if (entity == null) {
            return false;
        }
        return Persistence.getPersistenceUtil().isLoaded(entity);
    }
```
hope to generate something like
```java
    @Override
    public SubCategoryDto toDto(SubCategory entity) {
        if ( entity == null ) {
            return null;
        }
        if ( !isEntityAvailable( entity ) ) {
            return null;
        }
        SubCategoryDto.SubCategoryDtoBuilder<?, ?> subCategoryDto = SubCategoryDto.builder();
        subCategoryDto.id( entity.getId() );
        subCategoryDto.name( entity.getName() );
        subCategoryDto.nick( entity.getNick() );
        return SubCategoryDto.build();
    }
```
or just ignore it
```java
    @Override
    public SubCategoryDto toDto(SubCategory entity) {
        if ( entity == null ) {
            return null;
        }
        SubCategoryDto.SubCategoryDtoBuilder<?, ?> subCategoryDto = SubCategoryDto.builder();
        subCategoryDto.id( entity.getId() );
        subCategoryDto.name( entity.getName() );
        subCategoryDto.nick( entity.getNick() );
        return SubCategoryDto.build();
    }
```

### Actual behavior

but now I got this
```java
    @Override
    public SubCategoryDto toDto(SubCategory entity) {
        if ( entity == null ) {
            return null;
        }
        SubCategoryDto.SubCategoryDtoBuilder<?, ?> subCategoryDto = SubCategoryDto.builder();

        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.id( entity.getId() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.name( entity.getName() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.nick( entity.getNick() );
        }

        return SubCategoryDto.build();
    }
```

### Steps to reproduce the problem

using JPA with Mapstruct
I have a base interface:
```java
public interface EntityMapper<DTO extends EntityDto, E extends BasicEntity> {
    E toEntity(DTO dto);

    DTO toDto(E entity);

    // try to avoid JPA lazy loading issue
    // and this one worked well
    @Condition
    default boolean isCollectionAvailable(Collection<E> collection) {
        if (collection == null) {
            return false;
        }
        return Persistence.getPersistenceUtil().isLoaded(collection);
    }

    // try to avoid JPA lazy loading issue
    // got problem with this
    @Condition
    default boolean isEntityAvailable(E entity) {
        if (entity == null) {
            return false;
        }
        return Persistence.getPersistenceUtil().isLoaded(entity);
    }

    @MapperConfig(mappingControl = DeepClone.class,
                  mappingInheritanceStrategy = MappingInheritanceStrategy.AUTO_INHERIT_ALL_FROM_CONFIG)
    interface Config {
    }
}
```
and entity mappers:
```java
@Mapper(config = EntityMapper.Config.class, uses = {SubCategoryMapper.class})
public interface ParentCategoryMapper extends EntityMapper<ParentCategoryDto, ParentCategory> {
}

@Mapper(config = EntityMapper.Config.class, uses = {ParentCategoryMapper.class})
public interface SubCategoryMapper extends EntityMapper<SubCategoryDto, SubCategory> {
}
```
and then I got this:
```java
    @Override
    public SubCategoryDto toDto(SubCategory entity) {
        if ( entity == null ) {
            return null;
        }
        SubCategoryDto.SubCategoryDtoBuilder<?, ?> subCategoryDto = SubCategoryDto.builder();
        // Calling isEntityAvailable() so much times does not make any sense.
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.id( entity.getId() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.name( entity.getName() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.nick( entity.getNick() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.theOrder( entity.getTheOrder() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.icon( entity.getIcon() );
        }
        if ( isEntityAvailable( entity ) ) {
            subCategoryDto.link( entity.getLink() );
        }
        // this is right
        if ( ParentCategoryMapper.isEntityAvailable( entity.getParentCategory() ) ) {
            subCategoryDto.parentCategory( ParentCategoryMapper.toDto( entity.getParentCategory() ) );
        }
        return SubCategoryDto.build();
    }
```
and what I want is:
```java
    @Override
    public SubCategoryDto toDto(SubCategory entity) {
        if ( entity == null ) {
            return null;
        }
        if ( !isEntityAvailable( entity ) ) {
            return null;
        }
        SubCategoryDto.SubCategoryDtoBuilder<?, ?> subCategoryDto = SubCategoryDto.builder();
        subCategoryDto.id( entity.getId() );
        subCategoryDto.name( entity.getName() );
        subCategoryDto.nick( entity.getNick() );
        subCategoryDto.theOrder( entity.getTheOrder() );
        subCategoryDto.icon( entity.getIcon() );
        subCategoryDto.link( entity.getLink() );
        if ( ParentCategoryMapper.isEntityAvailable( entity.getParentCategory() ) ) {
            subCategoryDto.parentCategory( ParentCategoryMapper.toDto( entity.getParentCategory() ) );
        }
        return SubCategoryDto.build();
    }
```

### MapStruct Version

MapStruct 1.6.0.Beta1

### PR DESCRIPTION
**Pull request by filiphr**
This commit does a backwards incompatible change in regard to how presence check methods are used when only the source parameter is needed for the presence check. e.g.

```java
@Condition
public static boolean shouldMap(Employee employee) {
    // ...
}
```

is now only applied to source parameters or a property of type `Employee`. The method is no longer applied to all the parameters of a mapping method with a source parameter `Employee`. If you still want to do that then the method should be adapted

```java
@Condition
public static boolean shouldMap(Employee employee, @TargetPropertyName String targetPropertyName) {
    // ...
}
```

Instead of the `@TargetPropertyName` it can be `@SourcePropertyName`.

Fixes #2610 
Fixes #3459
Fixes #3270

NB: Perhaps we need to add some more tests for #3459 and #3270, I wanted to first see if this idea is worth pursuing.
-----

An alternative that we could do about the use of the right parameter would be if we introduce something like `@SourceParameter` and / or `@TargetProperty`. This people can explicitly decide if they want to apply a conditional method only on a source parameter or only on a target property. The 2 new annotations might also be used in other places

### CODE REVIEW

**Comment by thunderhook** [comment]
Sorry, I haven't had the time and mental complexity to think this through.
This is tricky, thanks for your effort in trying to tackle this issues.

Users would now have to provide the `@SourcePropertyName` or `@TargetPropertyName` just to get the condition to work (maybe like it used to).
So if the property name is unused (which it most likely will be), the IDE and other static code analysis tools will warn the user about the unused parameter. For example, we are currently improving our code quality with SonarQube, and false positives like this are a nuisance.
It also feels like a workaround.

So I would therefore prefer the second approach with the specific annotation, as you said "something like `@SourceParameter` and / or `@TargetProperty`".

Whichever way we go, users will still wonder why this is needed (e.g. "why do I have to add something extra?"). So this should be well documented in the docs and release notes.
But I also think that this backwards incompatible change needs to be done, and that this is the right time to do it.

I just played with your branch and saw that a condition written in the old way is simply not used. Is it possible to throw a compile error (or a warning)? (You have better insight into the underlying code)

**Comment by filiphr** [comment]
>Sorry, I haven't had the time and mental complexity to think this through.
This is tricky, thanks for your effort in trying to tackle this issues.

No rush, I've been working on this one for a while, it took me a bit of time to wrap my head properly around it as well. Thanks a lot for going through it.

>So I would therefore prefer the second approach with the specific annotation, as you said "something like `@SourceParameter` and / or `@TargetProperty`".

That was my gut feeling as well, or perhaps have a different annotation that would be applicable for source parameters condition check.

>I just played with your branch and saw that a condition written in the old way is simply not used.

I didn't like that at all as well. I'll look into an alternative for this

**Comment by filiphr** [comment]
@thunderhook, I gave another go at this. Basically, there is a new `@SourceCondition` (open to better naming suggestions) that should be used for source parameter checks. Let me know what you think about this approach

**Comment by thunderhook** [comment]
I really like this approach.

One thing I noticed while playing with the branch: Is there anything against a condition method being a `@SourceCondition` and a `@Condition` at the same time? I do not see why this should not be allowed. Maybe there are some scenarios where this is useful.

With the current implementation, the method won't be used if you add a `@Condition` there:
https://github.com/filiphr/mapstruct/blob/efc374163242119df2b27d83f412a0ce699b7bf9/processor/src/test/java/org/mapstruct/ap/test/conditional/basic/ConditionalMethodForSourceBeanMapper.java#L22

I haven't tried it explicitly, but I don't think it would be picked up as a presence check method either.

Otherwise, I really like it!

**Comment by filiphr** [comment]
You are indeed right. It won't be caught due to the `MethodFamilySelector`

```
method.getMethod().isObjectFactory() == criteria.isObjectFactoryRequired()
                && method.getMethod().isLifecycleCallbackMethod() == criteria.isLifecycleCallbackRequired()
                && method.getMethod().isPresenceCheck() == criteria.isPresenceCheckRequired()
                && method.getMethod().isSourceParameterCheck() == criteria.isSourceParameterCheckRequired()
```

I'll make sure that it works in that case as well.

I should also add some error handlings:

* Using `@SourceCondition` with `@TargetPropertyName` or `@SourcePropertyName` should lead to a compile error


An alternative to the `@SourceCondition`  could be something like:

```java
public enum ConditionStrategy {
    PROPERTIES,
    SOURCE_PARAMETERS,
}
```

then the condition would be

```java
@Target({ ElementType.METHOD })
@Retention(RetentionPolicy.CLASS)
public @interface Condition {

    ConditionStrategy[] appliesTo() default ConditionStrategy.PROPERTIES;

}
```

it can then be used

* `@Condition(appliesTo = ConditionStrategy.SOURCE_PARAMETERS)` - when we want to apply a condition only on source parameters
* `@Condition(appliesTo = { ConditionStrategy.PROPERTIES, ConditionStrategy.SOURCE_PARAMETERS})` - when it applied both to properties and source parameters

I am not sure which approach I like more. What do you think @thunderhook

**Comment by thunderhook** [comment]
I haven't fully thought this through, but I think the second approach might be more flexible when introducing conditions for other scenarios. Like collection items #1610 or `TARGET_PARAMETERS`. Don't know if there are other scenarios.

If there are other strategies added, then it would make sense to provide a `ConditionStrategy.ALL`.

Another idea might be to support both approaches. Where `@SourceCondition` is a meta-annotation like:

```java
@Condition( appliesTo = ConditionStrategy.SOURCE_PARAMETERS )
public @interface SourceCondition {

}
```

This would allow users to write their own Condition meta annotations, like:
```java
@Condition( appliesTo = { ConditionStrategy.SOURCE_PARAMETERS, ... } )
public @interface MyOwnEntityCondition {

}
```

However, this may cause problems if multiple annotations are set. Should it cause a compile error? If not, should they be combined? What has higher priority? 
```java
@SourceCondition
@Condition(appliesTo = { ConditionStrategy.PROPERTIES, ConditionStrategy.SOURCE_PARAMETERS})
Target map(Source source);
```

So maybe it's better to stick to one of these approaches rather than a combination of the two.

**Comment by filiphr** [comment]
Really good points @thunderhook. It would indeed work nicely for #1610 as well. That would basically be an additional `ConditionStrategy#ITERABLE_ELEMENTS`

>Another idea might be to support both approaches. Where `@SourceCondition` is a meta-annotation like:

I liked this even more. We could indeed provide `@SourceParameterCondition` or `@SourceCondition` that would be meta annotated with `@Condition(appliesTo = ConditionStrategy.SOURCE_PARAMETERS)`. Users can define their own annotations if they want to as well.

>However, this may cause problems if multiple annotations are set. Should it cause a compile error? If not, should they be combined? What has higher priority?

I don't think that this would cause problems. We would basically just merge all of the applicable `appliesTo` into a single set.

Thanks a lot for the feedback @thunderhook, I'll try to rework this in that direction :).

**Comment by filiphr** [comment]
@thunderhook I finally found the time to go over what we discussed last time. Can you please have a look at this and let me know what you think

File: core/src/main/java/org/mapstruct/SourceParameterCondition.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+ * </code></pre>
+ *
+ * @author Filip Hrisafov
+ * @since 1.6
+ * @see Condition @Condition
+ */
+@Target({ ElementType.METHOD })
+@Retention(RetentionPolicy.CLASS)
+@Condition(appliesTo = ConditionStrategy.SOURCE_PARAMETERS)
+public @interface SourceParameterCondition {
```
Comment (thunderhook) [inline core/src/main/java/org/mapstruct/SourceParameterCondition.java:72]: Have only seen usages with erroneus usages in tests. Can we alos have a happy case test?

**Review by thunderhook — COMMENTED** [review]
@filiphr I really like it. Just some small nitpicks.

The documentation can also be improved in another branch, if you want to merge it sooner than later.

File: core/src/main/java/org/mapstruct/SourceParameterCondition.java [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+ * The following parameters are accepted for the presence check methods:
+ *     <ul>
+ *         <li>The mapping source parameter</li>
+ *         <li>{@code @}{@link Context} parameter</li>
+ *     </ul>
+ *
+ * <strong>Note:</strong> The usage of this annotation is <em>mandatory</em>
+ * for a method to be considered as a source check method.
+ *
+ * <pre><code>
```
[the remark this answers is not in the document]
Comment (filiphr) [reply core/src/main/java/org/mapstruct/SourceParameterCondition.java:28]: Good point, I'll change it. I've also created #3588 so that we do it everywhere consistently.

File: core/src/main/java/org/mapstruct/Condition.java [hunk 3]
```diff
@@ -67,14 +75,22 @@
  *         return movieDto;
  *     }
  * }
- * </code>
- * </pre>
+ * </code></pre>
+ * <p>
+ * This annotation can also be used as a meta-annotation to define the condition strategy.
```
[the remark this answers is not in the document]
Comment (filiphr) [reply core/src/main/java/org/mapstruct/Condition.java:80]: Good point, I'll do it as part of this PR

File: core/src/main/java/org/mapstruct/SourceParameterCondition.java (hunk 1 above)
Comment (filiphr) [reply core/src/main/java/org/mapstruct/SourceParameterCondition.java:72]: Good point. I'll add a test with this as well. And also with the multiple applies to.

Comment (filiphr) [reply core/src/main/java/org/mapstruct/SourceParameterCondition.java:72]: Just checked, we are actually using this in `ConditionalMethodForSourceBeanMapper` actually.

**Comment by filiphr** [comment]
Thanks a lot for the review @thunderhook. All your comments make a lot of sense. I've added some docs, added a new test and also added the class to the `<code>` tag. Do you think that the doc is enough?

**Review by thunderhook — APPROVED** [review]
@filiphr Yes, I think this is enough. Thanks for your hard work on this. 👍 Merge at your own will!

**Comment by filiphr** [comment]
Thanks for the review @thunderhook
