### PR TITLE
#1242 Fix favoring of a single factory method with source params before others without source params.

### LINKED ISSUE #1242: Ambiguous factory method for @ObjectFactory with and without parameters
In the javadoc of the new `@ObjectFactory` we state:

> If there are two factory methods, both serving the same type, one with no parameters and one taking sources as input, then the one with the source parameters is favored. If there are multiple such factories, an ambiguity error is shown.

However, when that situation actually occurs. Currently we have compile error ambiguous factory methods. Should we update the implementation or the Javadoc?

### PR DESCRIPTION
**Pull request by agudian**
From the Javadoc of `@ObjectFactory`: If there are two factory methods, both serving the same type, one with no parameters and one taking sources as input, then the one with the source parameters is favored. If there are multiple such factories, an ambiguity error is shown.

Fixes #1242.

The test relies on #1237 being merged, so the PR will fail initially. I'll rebase after the review and after the other PR is merged.

### CODE REVIEW

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+ */
+public class FactoryParameterSelector implements MethodSelector {
+
+    @Override
+    public <T extends Method> List<SelectedMethod<T>> getMatchingMethods(Method mappingMethod,
+            List<SelectedMethod<T>> methods,
+            List<Type>sourceTypes,
+            Type targetType,
+            SelectionCriteria criteria) {
+        if ( !criteria.isObjectFactoryRequired() || methods.size() <= 1 ) {
```
Comment (filiphr) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java]: For the future I think that we need to extract a `supports` method on the `MethodSelector` almost all of them have some condition that just returns. However, it might be an overkill as well.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+    TargetFactories.class
+})
+public class Issue1242Test {
+    @Test
+    public void factoryMethodWithSourceParamIsChosen() {
+        SourceA sourceA = new SourceA();
+        sourceA.setB( new SourceB() );
+
+        TargetA targetA = new TargetA();
+        Mappers.getMapper( Issue1242Mapper.class ).mergeA( sourceA, targetA );
```
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java]: Does this slow down the tests a bit?

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java (hunk 1 above)
Comment (agudian) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/selector/FactoryParameterSelector.java]: Yeah, maybe. If it makes stuff more readable for us 🙂

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java (hunk 2 above)
Comment (agudian) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java]: What exactly do you mean?

**Comment by filiphr** [comment]
@agudian can you please rebase this on master. There is some issue with codecov. I don't know why but the commit it is picking up is not correct.

File: processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java (hunk 2 above)
Comment (filiphr) [inline processor/src/test/java/org/mapstruct/ap/test/bugs/_1242/Issue1242Test.java]: Well we call twice `Mapper.getMapper( Issue1242Mapper.class )` . Don't we recommend users having a `public static final` field to store the reference. In any case, I didn't mean it for you to change it, just wanted to mention it.

**Comment by agudian** [comment]
Rebased :)

**Comment by filiphr** [comment]
Merged, thanks for the PR @agudian
